# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQAItem',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verified', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('/', 'N/A')], max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
            ],
            options={
                'db_table': 'order_qa_item',
            },
        ),
        migrations.CreateModel(
            name='QAType',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qa_type',
            },
        ),
        migrations.CreateModel(
            name='QAItem',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('qa_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quality.QAType')),
            ],
            options={
                'db_table': 'qa_item',
            },
        ),
        migrations.CreateModel(
            name='OrderQAItemPhoto',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='skus')),
                ('order_qa_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quality.OrderQAItem')),
            ],
            options={
                'db_table': 'order_qa_item_photo',
            },
        ),
        migrations.AddField(
            model_name='orderqaitem',
            name='qa_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quality.QAItem'),
        ),
    ]
