# Generated by Django 2.2.7 on 2020-01-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialfeature',
            name='sku_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='caravans.SKUCategory'),
        ),
    ]
