# Generated by Django 2.2.7 on 2020-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200124_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderseries',
            name='production_unit1',
            field=models.IntegerField(default=1),
        ),
    ]
