# Generated by Django 2.2.7 on 2020-02-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderseries_production_unit1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderseries',
            old_name='production_unit1',
            new_name='production_unit',
        ),
    ]
