# Generated by Django 2.2.7 on 2020-02-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200204_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderseries',
            name='production_unit',
        ),
    ]
