# Generated by Django 2.2.7 on 2020-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderseries_production_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderseries',
            name='production_unit',
            field=models.IntegerField(default=1),
        ),
    ]
