# Generated by Django 2.2.7 on 2021-02-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210226_2037'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='order',
        #     name='appretail_opportunity_no',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_status',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_title',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
        # migrations.AlterField(
        #     model_name='orderdocument',
        #     name='type',
        #     field=models.IntegerField(choices=[(1, 'Customer Plan'), (2, 'Factory Plan'), (3, 'Chassis Plan'), (4, 'Contract'), (5, 'Handover to driver form'), (6, 'Handover to dealership form'), (7, 'Plumbing Certificate'), (8, 'Electrical Certificate'), (9, 'Weighbridge Certificate'), (10, 'Quality Control Certificate'), (11, 'Other Certificates')]),
        # ),
        # migrations.CreateModel(
        #     name='CertificateDeleted',
        #     fields=[
        #         ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('doc_id', models.CharField(blank=True, max_length=500)),
        #         ('cert_title', models.CharField(blank=True, max_length=500)),
        #         ('cert_status', models.CharField(blank=True, max_length=500)),
        #         ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
        #     ],
        #     options={
        #         'verbose_name': 'Certificates Deleted',
        #         'verbose_name_plural': 'Certificates Deleted Details',
        #         'db_table': 'certificates_deleted',
        #         'ordering': ('order',),
        #     },
        # ),
    ]
