# Generated by Django 2.2.7 on 2021-03-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210303_2126'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='order',
        #     options={'permissions': (('view_order_all', 'Can view all orders'), ('view_order_own', 'Can view own orders'), ('view_production_data', 'Can view production data'), ('print_for_autocad', 'Can print Order for AutoCAD'), ('create_order_all', 'Can create new orders for all dealerships'), ('create_order_own', 'Can create new orders only for assigned dealerships'), ('modify_order_all', 'Can modify all orders'), ('modify_order_dealership', 'Can modify orders for assigned dealership'), ('modify_order_finalized', 'Can modify an order after it has been finalised'), ('request_order_approval', 'Request for an order to be approved: Step 1 in approval workflow'), ('approve_order_all', 'Approve any order and pass it to production for build scheduling: Step 2 in approval workflow'), ('approve_order_own', 'Approve order in own dealership only and pass it to production for build scheduling: Step 2 in approval workflow'), ('override_dealer_capacity', 'Can override dealership capacity set and move orders to another production Month'), ('cancel_order', 'Cancel any order'), ('finalize_order_all', 'Finalise an order: Step 3 in approval workflow'), ('cancel_finalization', 'Reverse order finalisation'), ('view_order_cost_price', 'View the cost price for an order'), ('view_order_trade_price_all', 'View the trade price for all orders'), ('view_order_retail_price', 'View the retail price for an order'), ('modify_order_trade_price', 'Can modify the trade price for all orders'), ('modify_order_retail_price', 'Can modify the retail price for an order'), ('modify_order_other_prices_all', 'Can modify prices for an order (including retail, dealer load, trade-in and comments'), ('modify_order_deposit', 'Can modify the deposit paid on an order'), ('modify_chassis_number', 'Can assign a chassis number for an order'), ('modify_order_drafter', 'Can modify drafter for an order'), ('modify_order_qc_date_planned', 'Can modify the planned QC date for an order'), ('modify_order_qc_date_actual', 'Can modify the actual QC date for an order'), ('modify_order_vin_number', 'Can modify VIN Number for an order'), ('modify_order_weights', 'Can modify weights for an order'), ('modify_order_dispatch_date_planned', 'Can modify the planned dispatch date for an order'), ('modify_order_dispatch_date_actual', 'Can modify the actual dispatch date for an order'), ('update_handover_to_driver_form', 'Can update the handover to driver form for an order'), ('modify_order_received_date_dealership', 'Can modify the dealership received date for an order'), ('update_handover_to_dealership_form', 'Can update the handover to dealership form for an order'), ('modify_order_delivery_date_customer', 'Can modify customer delivery date for an order'), ('print_invoice_all', 'Can print invoice for all orders'), ('print_invoice_own', 'Can print invoice for own orders'), ('reassign_order_all', 'Can reassign orders'), ('reassign_stock_orders', 'Can assign stock orders to a different Dealership'), ('approve_special_features', 'Can approve or reject special features'), ('modify_special_features_wholesale', 'Can modify the wholesale price of special features'), ('modify_special_features', 'Can modify the detailed special features'), ('set_custom_series', 'Can set a custom series name and code'), ('view_schedule_availability', 'Can view the Schedule Availability screen'), ('manual_override', 'Can manually override any value'), ('replace_sku', 'Can use the "Replace SKU" function'))},
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='appretail_opportunity_no',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_status',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_title',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
        # migrations.AlterField(
        #     model_name='orderdocument',
        #     name='type',
        #     field=models.IntegerField(choices=[(1, 'Customer Plan'), (2, 'Factory Plan'), (3, 'Chassis Plan'), (4, 'Contract'), (5, 'Handover to driver form'), (6, 'Handover to dealership form'), (7, 'Plumbing Certificate'), (8, 'Electrical Certificate'), (9, 'Weighbridge Certificate'), (10, 'Quality Control Certificate'), (11, 'Other Certificates')]),
        # ),
        # migrations.CreateModel(
        #     name='CertificateDeleted',
        #     fields=[
        #         ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('doc_id', models.CharField(blank=True, max_length=500)),
        #         ('cert_title', models.CharField(blank=True, max_length=500)),
        #         ('cert_status', models.CharField(blank=True, max_length=500)),
        #         ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
        #     ],
        #     options={
        #         'verbose_name': 'Certificates Deleted',
        #         'verbose_name_plural': 'Certificates Deleted Details',
        #         'db_table': 'certificates_deleted',
        #         'ordering': ('order',),
        #     },
        # ),
    ]
