# Generated by Django 2.2.7 on 2020-02-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
