# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warranty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caravans', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('creation_time', models.DateTimeField()),
                ('sku_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Not Actioned'), (2, 'Requested Quote'), (3, 'Under Approval'), (4, 'Under Repair'), (5, 'Completed')])),
                ('repairer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_fixed', models.DateField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU')),
            ],
            options={
                'db_table': 'warranty_claim',
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('photo', models.ImageField(upload_to=warranty.models.warranty_image_path)),
                ('warranty_claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warranty.WarrantyClaim')),
            ],
            options={
                'db_table': 'warranty_claim_photo',
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('creation_time', models.DateTimeField()),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('warranty_claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warranty.WarrantyClaim')),
            ],
            options={
                'db_table': 'warranty_claim_note',
            },
        ),
    ]
