# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('caravans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('day', models.DateField(unique=True, verbose_name='Day')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('type', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open'), (2, 'Holiday')], default=0)),
                ('holiday_name', models.CharField(blank=True, max_length=255, verbose_name='Holiday')),
            ],
            options={
                'verbose_name': 'Production Capacity',
                'verbose_name_plural': 'Production Capacities',
                'db_table': 'schedule_capacity',
            },
        ),
        migrations.CreateModel(
            name='ContractorScheduleExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('production_date_offset', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MonthPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_month', models.DateField(help_text='The first day of the month represented by this model.', unique=True)),
                ('production_start_date', models.DateField(blank=True, help_text='The date when the production actually starts for this month.', null=True)),
                ('sign_off_reminder', models.DateField()),
                ('sign_off_reminder_sent', models.BooleanField(default=False)),
                ('draft_completion', models.DateField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransport',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_production_date', models.DateField(blank=True, null=True)),
                ('actual_production_comments', models.TextField(null=True)),
                ('planned_watertest_date', models.DateField(blank=True, null=True)),
                ('actual_watertest_date', models.DateField(blank=True, null=True)),
                ('qc_comments', models.TextField(null=True)),
                ('watertest_comments', models.TextField(null=True)),
                ('dispatch_comments', models.TextField(null=True)),
                ('final_qc_date', models.DateField(blank=True, null=True)),
                ('final_qc_comments', models.TextField(null=True)),
                ('chassis_section', models.DateField(blank=True, null=True)),
                ('chassis_section_comments', models.TextField(null=True)),
                ('building', models.DateField(blank=True, null=True)),
                ('building_comments', models.TextField(null=True)),
                ('hold_caravans', models.BooleanField(default=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Order OrderTransport Details',
                'verbose_name_plural': 'Order OrderTransport Details',
                'db_table': 'ordertransport',
            },
        ),
        migrations.CreateModel(
            name='ContractorScheduleExportColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('contractor_description_field', models.CharField(choices=[('description', 'Use item description'), ('contractor_description1', 'Contractor desc 1'), ('contractor_description2', 'Contractor desc 2'), ('contractor_description3', 'Contractor desc 3'), ('contractor_description4', 'Contractor desc 4'), ('contractor_description5', 'Contractor desc 5')], default='description', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKUCategory')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.ContractorScheduleExport')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
    ]
