# Generated by Django 2.2.7 on 2020-01-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191229_2237'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordertransport',
            table='orders_transport',
        ),
    ]
