# Generated by Django 2.2.7 on 2020-02-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0004_auto_20200204_1428'),
        ('orders', '0004_auto_20200204_1413'),
        ('schedule', '0004_auto_20200114_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('production_unit', models.IntegerField(default=1)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.Series')),
            ],
            options={
                'verbose_name': 'Production Unit Details',
                'verbose_name_plural': 'Production Unit Details',
                'db_table': 'schedule_unit',
            },
        ),
    ]
