# Generated by Django 2.2.7 on 2020-02-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_productionunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
    ]
