# Generated by Django 2.2.7 on 2020-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200204_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionUnit',
        ),
    ]
