# Generated by Django 2.2.7 on 2020-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_monthplanning_production_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthplanning',
            name='production_month',
            field=models.DateField(help_text='The first day of the month represented by this model.'),
        ),
        migrations.AlterUniqueTogether(
            name='monthplanning',
            unique_together={('production_month', 'production_unit')},
        ),
    ]
