# Generated by Django 2.2.7 on 2020-02-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20200207_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.ProductionUnit'),
        ),
        migrations.AlterField(
            model_name='monthplanning',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.ProductionUnit'),
        ),
    ]
