# Generated by Django 2.2.7 on 2020-12-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200213_1914'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='actual_watertest_date',
        #     new_name='plumbing_date',
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='planned_watertest_date',
        #     new_name='purchase_order_raised_date',
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='email_sent',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='senior_designer_verfied_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='capacity',
        #     name='production_unit',
        #     field=models.IntegerField(choices=[(1, 'Caravans'), (2, 'Pop-Top/Campers')]),
        # ),
        # migrations.AlterField(
        #     model_name='monthplanning',
        #     name='production_unit',
        #     field=models.IntegerField(choices=[(1, 'Caravans'), (2, 'Pop-Top/Campers')]),
        # ),
    ]
