# Generated by Django 2.2.7 on 2019-12-29 10:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=77)),
                ('role', models.IntegerField(blank=True, choices=[(None, 'None'), (3, 'Sign off reminder'), (5, 'Order Submitted'), (6, 'Customer Plans Rejected'), (7, 'Special Features Rejected'), (8, 'Order Finalise Notification')], null=True, unique=True)),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
