# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='new_customer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.CustomerStatus'),
        ),
    ]
