# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import production.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Order')),
                ('build_date_original', models.DateField(null=True, verbose_name='Build Date')),
                ('build_date', models.DateField(db_index=True, null=True, verbose_name='Build Date')),
                ('build_priority', models.IntegerField(choices=[(1, 'ASAP'), (2, 'Fixed'), (3, 'Tentative')], default=3, verbose_name='Build Status')),
                ('drawing_on', models.DateTimeField(null=True, verbose_name='Drawings completed')),
                ('drawing_to_prod_on', models.DateTimeField(null=True, verbose_name='Drawings to Production on')),
                ('chassis_ordered_on', models.DateTimeField(null=True, verbose_name='Chassis Ordered on')),
                ('coils_ordered_on', models.DateTimeField(null=True, verbose_name='Coils Ordered by')),
                ('frame_galvanized', models.NullBooleanField(verbose_name='Galvanised Frame?')),
                ('qc_date_planned', models.DateField(null=True)),
                ('qc_date_actual', models.DateField(null=True)),
                ('vin_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='VIN Appointed')),
                ('weight_tare', models.IntegerField(null=True)),
                ('weight_atm', models.IntegerField(null=True)),
                ('weight_tow_ball', models.IntegerField(null=True)),
                ('weight_tyres', models.CharField(blank=True, max_length=15, null=True)),
                ('weight_chassis_gtm', models.IntegerField(null=True)),
                ('weight_gas_comp', models.IntegerField(null=True)),
                ('weight_payload', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Order Build Details',
                'verbose_name_plural': 'Order Build Details',
                'db_table': 'build',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BuildOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_month', models.DateField()),
                ('order_number', models.IntegerField(unique_for_month='production_month')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('section', models.IntegerField(choices=[(10, 'Production'), (20, 'Quality Control'), (30, 'Notes')])),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Build Checklist',
                'db_table': 'build_checklist',
            },
        ),
        migrations.CreateModel(
            name='CoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Coil Type')),
            ],
            options={
                'verbose_name': 'Coil Type',
                'db_table': 'build_coil_type',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('recorded_on', models.DateTimeField(verbose_name='Recorded on')),
                ('status', models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'NA')])),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Build')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
            ],
            options={
                'verbose_name': 'Build Outcome',
                'db_table': 'build_outcome',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Checklist')),
            ],
            options={
                'verbose_name': 'Build Step',
                'db_table': 'build_step',
            },
        ),
        migrations.CreateModel(
            name='OutcomeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('recorded_on', models.DateTimeField()),
                ('text', models.TextField()),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.Outcome')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Build Outcome Note',
                'db_table': 'build_outcome_note',
            },
        ),
        migrations.CreateModel(
            name='OutcomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('image_file', models.ImageField(max_length=255, upload_to=production.models._invoke_image_file_path)),
                ('recorded_on', models.DateTimeField()),
                ('is_shared', models.BooleanField(default=False)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.Outcome')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Build Outcome Image',
                'db_table': 'build_outcome_image',
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Step'),
        ),
        migrations.CreateModel(
            name='BuildNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('recorded_on', models.DateTimeField()),
                ('text', models.TextField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Build')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Checklist')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Build Note',
                'db_table': 'build_note',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='build_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='production.BuildOrder'),
        ),
        migrations.AddField(
            model_name='build',
            name='chassis_ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='build_chassis_ordered_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Chassis Ordered by'),
        ),
        migrations.AddField(
            model_name='build',
            name='coil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.CoilType', verbose_name='Coil Type'),
        ),
        migrations.AddField(
            model_name='build',
            name='coils_ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='build_coils_ordered_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Coils Ordered on'),
        ),
        migrations.AddField(
            model_name='build',
            name='drafter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Drafter Appointed'),
        ),
        migrations.AddField(
            model_name='build',
            name='drawing_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='build_drawing_set', to=settings.AUTH_USER_MODEL, verbose_name='Drawings completed by'),
        ),
        migrations.AddField(
            model_name='build',
            name='drawing_to_prod_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='build_drawing_to_prod_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Drawings to Production by'),
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('build', 'step')},
        ),
        migrations.CreateModel(
            name='ChecklistOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateTimeField(verbose_name='Recorded on')),
                ('is_complete', models.NullBooleanField(choices=[(None, 'Default'), (False, 'Override as incomplete'), (True, 'Override as complete')], verbose_name='Completion Override')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Build')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Checklist')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
            ],
            options={
                'verbose_name': 'Build Checklist Override',
                'db_table': 'build_checklist_override',
                'permissions': (('modify_checklistoverride', 'Can set build checklist overrides'),),
                'default_permissions': (),
                'unique_together': {('build', 'checklist')},
            },
        ),
    ]
