# Generated by Django 2.2.7 on 2020-02-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildorder',
            name='production_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buildorder',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='buildorder',
            unique_together={('production_month', 'order_number', 'production_unit')},
        ),
    ]
