# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newage', '0001_initial'),
        ('caravans', '0002_auto_20191229_2147'),
        ('customers', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointed_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dealerships.Dealership'),
        ),
        migrations.AddField(
            model_name='customer',
            name='appointed_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.CustomerStatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_delivery_address', to='newage.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caravans.Series'),
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_physical_address', to='newage.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_postal_address', to='newage.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_of_awareness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.SourceOfAwareness'),
        ),
    ]
