# Generated by Django 2.2.7 on 2020-02-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191229_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceofawareness',
            options={'verbose_name_plural': 'Source Of Awareness'},
        ),
    ]
