# Generated by Django 2.2.7 on 2020-02-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200212_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerstatus',
            options={'verbose_name_plural': 'Customer Status'},
        ),
    ]
