# Generated by Django 2.2.7 on 2020-02-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200212_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceofawareness',
            options={'verbose_name_plural': 'Source of Awareness'},
        ),
    ]
