# Generated by Django 2.2.7 on 2020-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200212_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default=0, editable=False, max_length=80),
        ),
    ]
