# Generated by Django 2.2.7 on 2020-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(editable=False, max_length=80),
        ),
    ]
