# Generated by Django 2.2.7 on 2019-12-29 10:47

import caravans.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hourly_rate', models.FloatField()),
            ],
            options={
                'db_table': 'labour_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('logo', models.ImageField(upload_to=caravans.models.model_logo_path)),
            ],
            options={
                'db_table': 'model',
                'ordering': ('name',),
                'permissions': (('browse_all_models', 'Can browse all models'),),
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'raw_material',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'Add Extras'), (2, 'Make Selection'), (3, 'Display Warning'), (4, 'Customer Entry Details'), (5, 'Multiply Price'), (6, 'Add Production Note'), (7, 'Mark on Plan'), (8, 'Force Selection'), (10, 'Force Unselection'), (9, 'Price Adjustment Based on Selection')])),
                ('text', models.TextField()),
                ('price_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ('title', 'type'),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_feet', models.IntegerField(blank=True, null=True)),
                ('length_inches', models.IntegerField(blank=True, null=True)),
                ('length_incl_aframe_feet', models.IntegerField(blank=True, null=True)),
                ('length_incl_aframe_inches', models.IntegerField(blank=True, null=True)),
                ('length_incl_bumper_feet', models.IntegerField(blank=True, null=True)),
                ('length_incl_bumper_inches', models.IntegerField(blank=True, null=True)),
                ('height_max_incl_ac_feet', models.IntegerField(blank=True, null=True)),
                ('height_max_incl_ac_inches', models.IntegerField(blank=True, null=True)),
                ('width_feet', models.IntegerField(blank=True, null=True)),
                ('width_inches', models.IntegerField(blank=True, null=True)),
                ('width_incl_awning_feet', models.IntegerField(blank=True, null=True)),
                ('width_incl_awning_inches', models.IntegerField(blank=True, null=True)),
                ('avg_tare_weight_min', models.IntegerField(blank=True, null=True)),
                ('avg_tare_weight_max', models.IntegerField(blank=True, null=True)),
                ('avg_ball_weight_min', models.IntegerField(blank=True, null=True)),
                ('avg_ball_weight_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'db_table': 'series',
                'ordering': ('model__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=caravans.models.sku_image_path)),
                ('quantity', models.FloatField(default=1)),
                ('public_description', models.CharField(max_length=512, null=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Show on Specification')),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('contractor_description1', models.CharField(blank=True, max_length=512, null=True)),
                ('contractor_description2', models.CharField(blank=True, max_length=512, null=True)),
                ('contractor_description3', models.CharField(blank=True, max_length=512, null=True)),
                ('contractor_description4', models.CharField(blank=True, max_length=512, null=True)),
                ('contractor_description5', models.CharField(blank=True, max_length=512, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'db_table': 'sku',
                'ordering': ('name',),
                'permissions': (('import_sku', "Can Import SKU's"), ('export_sku', "Can Export SKU's")),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_bom_report_visible', models.BooleanField(default=True)),
                ('is_bom_ostendo_exportable', models.BooleanField(default=True)),
                ('is_bom_csv_exportable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'uom',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SKURawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('quantity', models.FloatField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.RawMaterial')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU')),
            ],
            options={
                'db_table': 'sku_raw_material',
            },
        ),
        migrations.CreateModel(
            name='SKULabour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('building_time', models.FloatField()),
                ('labour_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.LabourType')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU')),
            ],
            options={
                'verbose_name': 'Series Labour',
                'verbose_name_plural': 'Series Labour',
                'db_table': 'sku_labour',
            },
        ),
        migrations.CreateModel(
            name='SKUCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_order', models.IntegerField()),
                ('print_order', models.IntegerField()),
                ('read_only', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caravans.SKUCategory')),
            ],
            options={
                'verbose_name': 'SKU Category',
                'verbose_name_plural': 'SKU Categories',
                'db_table': 'sku_category',
                'ordering': ('screen_order', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.SKUCategory'),
        ),
        migrations.AddField(
            model_name='sku',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caravans.Supplier'),
        ),
        migrations.CreateModel(
            name='SeriesSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('availability_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'Upgrade'), (3, 'Not Used'), (4, 'Optional Extra'), (5, 'Selection')])),
                ('is_visible_on_spec_sheet', models.BooleanField(default=False)),
                ('contractor_description', models.CharField(blank=True, max_length=512, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.Series')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU')),
            ],
            options={
                'verbose_name': 'Series SKU',
                'verbose_name_plural': 'Series SKUs',
                'db_table': 'series_sku',
            },
        ),
        migrations.CreateModel(
            name='SeriesPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('photo', models.ImageField(null=True, upload_to=caravans.models.series_image_path)),
                ('is_main_photo', models.BooleanField(default=False)),
                ('is_floor_plan', models.BooleanField(default=False)),
                ('brochure_order', models.IntegerField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.Series')),
            ],
            options={
                'verbose_name': 'Series Photo',
                'verbose_name_plural': 'Series Photos',
                'db_table': 'series_photo',
                'ordering': ['series__code', '-is_main_photo'],
            },
        ),
    ]
