# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caravans', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dealerships',
            field=models.ManyToManyField(blank=True, to='dealerships.Dealership'),
        ),
        migrations.AddField(
            model_name='series',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.Model'),
        ),
        migrations.AddField(
            model_name='rule',
            name='associated_skus',
            field=models.ManyToManyField(blank=True, related_name='associated_skus', to='caravans.SKU'),
        ),
        migrations.AddField(
            model_name='rule',
            name='series',
            field=models.ManyToManyField(blank=True, to='caravans.Series'),
        ),
        migrations.AddField(
            model_name='rule',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.UOM'),
        ),
    ]
