# Generated by Django 2.2.7 on 2020-02-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0002_auto_20191229_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='production_unit1',
            field=models.IntegerField(choices=[(1, 'Schedule I'), (2, 'Schedule II')], default=1),
            preserve_default=False,
        ),
    ]
