# Generated by Django 2.2.7 on 2020-02-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0003_series_production_unit1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='production_unit1',
            new_name='production_unit',
        ),
    ]
