# Generated by Django 2.2.7 on 2020-02-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0005_auto_20200212_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionunit',
            options={},
        ),
        migrations.AlterModelTable(
            name='productionunit',
            table='schedule_unit',
        ),
    ]
