# Generated by Django 2.2.7 on 2020-02-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0006_auto_20200212_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionunit',
            options={'ordering': ('id',), 'verbose_name_plural': 'ProductionUnit'},
        ),
        migrations.RemoveField(
            model_name='series',
            name='production_unit1',
        ),
        migrations.AlterField(
            model_name='series',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravans.ProductionUnit'),
        ),
    ]
