# Generated by Django 2.2.7 on 2020-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0008_auto_20200212_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='unit_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
