# Generated by Django 2.2.7 on 2019-12-29 10:47

import dealerships.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtools', '0003_auto_20160128_0912'),
        ('newage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=dealerships.models.dealership_logo_path)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('egm_implementation_date', models.DateField(blank=True, null=True, verbose_name=' eGM implementation date')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newage.Address')),
            ],
            options={
                'db_table': 'dealership',
            },
        ),
        migrations.CreateModel(
            name='DealershipUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealership Staff',
                'verbose_name_plural': 'Dealership Staff',
                'db_table': 'dealership_user',
            },
            bases=('authtools.user',),
        ),
        migrations.CreateModel(
            name='DealershipUserDealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('is_principal', models.BooleanField(verbose_name='Principal?')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_ref', to='dealerships.Dealership')),
                ('dealership_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ref', to=settings.AUTH_USER_MODEL)),
                ('dealership_user_dealership_ref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_user_ref', to='dealerships.DealershipUser')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='dealershipuser',
            name='dealerships',
            field=models.ManyToManyField(related_name='deal_ref', through='dealerships.DealershipUserDealership', to='dealerships.Dealership'),
        ),
    ]
