# Generated by Django 2.2.7 on 2019-12-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershipuserdealership',
            name='dealership_user_dealership_ref',
        ),
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ref', to='dealerships.DealershipUser'),
        ),
    ]
