# Generated by Django 2.2.7 on 2019-12-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0002_auto_20191229_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipuserdealership',
            name='dealership_user_dealership_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_user_ref', to='dealerships.DealershipUser'),
        ),
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ref', to=settings.AUTH_USER_MODEL),
        ),
    ]
