# Generated by Django 2.2.7 on 2019-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0004_auto_20191229_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipuser',
            name='dealerships',
            field=models.ManyToManyField(through='dealerships.DealershipUserDealership', to='dealerships.Dealership'),
        ),
    ]
