# Generated by Django 2.2.7 on 2019-12-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0005_auto_20191229_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealerships.Dealership'),
        ),
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
