# Generated by Django 2.2.7 on 2019-12-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0006_auto_20191229_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerships.Dealership'),
        ),
        migrations.AlterField(
            model_name='dealershipuserdealership',
            name='dealership_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
