# Generated by Django 2.2.7 on 2020-01-14 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0007_auto_20191230_0045'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='dealershipuserdealership',
#            name='dealership',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealerships.Dealership'),
#        ),
#        migrations.AlterField(
#            model_name='dealershipuserdealership',
#            name='dealership_user',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealerships.DealershipUser'),
#        ),
#        migrations.AlterField(
#            model_name='dealershipuserdealership',
#            name='dealership_user_dealership_ref',
#            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_user_ref', to=settings.AUTH_USER_MODEL),
#        ),
    ]
