# Generated by Django 2.2.7 on 2020-01-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0009_auto_20200114_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershipuserdealership',
            name='dealership_user_dealership_ref',
        ),
    ]
