# Generated by Django 2.2.7 on 2020-01-24 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealerships', '0012_remove_dealershipuserdealership_dealership_user_dealership_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipuserdealership',
            name='dealership_user_dealership_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_user_ref', to=settings.AUTH_USER_MODEL),
        ),
    ]
