# Generated by Django 2.2.7 on 2020-01-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0013_dealershipuserdealership_dealership_user_dealership_ref'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='dealershipuserdealership',
#            name='dealership_user_dealership_ref',
#        ),
    ]
