# Generated by Django 2.2.7 on 2019-12-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted')])),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('saved_on', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_repr', models.CharField(max_length=512)),
                ('use_content_repr_as_action', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_audit_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'index_together': {('object_id', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='AuditField',
            fields=[
                ('name', models.CharField(max_length=128, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_from', models.TextField(null=True)),
                ('changed_to', models.TextField(null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='audit.Audit')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
